apiVersion: configplane.juniper.net/v1alpha1
kind: Kubemanager
metadata:
  name: contrail-k8s-kubemanager
  namespace: contrail
spec:
  common:
    containers:
    - image: hub.juniper.net/cn2/contrail-k8s-kubemanager:22.2.0.93
      name: contrail-k8s-kubemanager
    nodeSelector:
      node-role.kubernetes.io/master: ""
