apiVersion: configplane.juniper.net/v1alpha1
kind: Kubemanager
metadata:
  name: contrail-k8s-kubemanager
  namespace: contrail
spec:
  common:
    containers:
    - image: enterprise-hub.juniper.net/contrail-container-prod/contrail-k8s-kubemanager:22.2.0.100
      name: contrail-k8s-kubemanager
    nodeSelector:
      node-role.kubernetes.io/master: ""
