apiVersion: controlplane.juniper.net/v1alpha1
kind: Control
metadata:
  name: contrail-control
  namespace: contrail
spec:
  common:
    containers:
    - image: enterprise-hub.juniper.net/contrail-container-prod/contrail-control:22.2.0.93
      name: contrail-control
    - image: enterprise-hub.juniper.net/contrail-container-prod/contrail-telemetry-exporter:22.2.0.93
      name: contrail-control-telemetry-exporter
    initContainers:
    - image: enterprise-hub.juniper.net/contrail-container-prod/contrail-init:22.2.0.93
      name: contrail-init
    nodeSelector:
      node-role.kubernetes.io/master: ""
