apiVersion: checks.contrail.juniper.net/v1alpha1
kind: ContrailReadiness
metadata:
  name: contrail-uninstall
spec:
  manifestConfigMapName: deployer-yaml
  tasks:
    - name: cn2uninstall
      allowFailure: false
      atomicTask: false
      # Running this check on one node should be sufficient
      # Set a label that matches exactly one node to do so.
      # Running on all nodes would work, but is redundant.
      # nodeSelector:
      #   matchLabels:
      #     kubernetes.io/hostname: <master-node-hostname>
      taskPodSpec:
        serviceAccountName: contrail-readiness-serviceaccount
        hostNetwork: true
        restartPolicy: Never
        containers:
          - name: cn2uninstall
            image: enterprise-hub.juniper.net/contrail-container-prod/contrail-readiness-tasks:R23.1-282
            imagePullPolicy: Always
            command: ["/cn2uninstall"]
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        tolerations:
          - key: "key"
            operator: "Equal"
            value: "value"
            effect: "NoSchedule"
