apiVersion: configplane.juniper.net/v1
kind: Controller
metadata:
  name: contrail-k8s-controller
  namespace: contrail-system
spec:
  common:
    containers:
    - env:
      - name: LOG_CONFIG_FILE
        value: /etc/config/cm/config.yaml
      - name: XDG_CACHE_HOME
        value: /tmp
      image: enterprise-hub.juniper.net/contrail-container-internal/contrail-k8s-controller:23.3.0.98
      name: contrail-k8s-controller
      volumeMounts:
      - mountPath: /etc/config/cm
        name: config
    serviceAccountName: contrail-system-serviceaccount
    volumes:
    - configMap:
        items:
        - key: config.yaml
          path: config.yaml
        name: contrail-k8s-controller-cm
      name: config
