apiVersion: controlplane.juniper.net/v1alpha1
kind: Control
metadata:
  name: contrail-control
  namespace: contrail
spec:
  xmppAuthEnable: true
  introspectSslEnable: true
  sandeshSslEnable: true
  common:
    containers:
    - image: enterprise-hub.juniper.net/contrail-container-prod/contrail-control:23.3.0.181
      name: contrail-control
    - image: enterprise-hub.juniper.net/contrail-container-prod/contrail-telemetry-exporter:23.3.0.181
      name: contrail-control-telemetry-exporter
    initContainers:
    - image: enterprise-hub.juniper.net/contrail-container-prod/contrail-init:23.3.0.181
      name: contrail-init