apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
  namespace: contrail-deploy
data:
  .dockerconfigjson: <base64-encoded-credential>
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-deploy-serviceaccount
  namespace: contrail-deploy
imagePullSecrets:
- name: registrypullsecret
