apiVersion: controlplane.juniper.net/v1alpha1
kind: Control
metadata:
  name: contrail-control
  namespace: contrail
spec:
  xmppAuthEnable: true
  introspectSslEnable: true
  common:
    containers:
    - image: enterprise-hub.juniper.net/contrail-container-early/contrail-control:22.4.0.48
      name: contrail-control
    - image: enterprise-hub.juniper.net/contrail-container-early/contrail-telemetry-exporter:22.4.0.48
      name: contrail-control-telemetry-exporter
    initContainers:
    - image: enterprise-hub.juniper.net/contrail-container-early/contrail-init:22.4.0.48
      name: contrail-init