apiVersion: dataplane.juniper.net/v1alpha1
kind: Vrouter
metadata:
  name: contrail-vrouter-masters
  namespace: contrail
spec:
  agent:
    default:
      xmppAuthEnable: true
      httpServerPort: 18085
    sandesh:
      introspectSslEnable: true
  common:
    containers:
    - image: enterprise-hub.juniper.net/contrail-container-internal/contrail-vrouter-agent:R22.4-99
      name: contrail-vrouter-agent
    - image: enterprise-hub.juniper.net/contrail-container-internal/contrail-init:R22.4-99
      name: contrail-watcher
    - image: enterprise-hub.juniper.net/contrail-container-internal/contrail-telemetry-exporter:R22.4-99
      name: contrail-vrouter-telemetry-exporter
    initContainers:
    - image: enterprise-hub.juniper.net/contrail-container-internal/contrail-init:R22.4-99
      name: contrail-init
    - image: enterprise-hub.juniper.net/contrail-container-internal/contrail-cni-init:R22.4-99
      name: contrail-cni-init