apiVersion: dataplane.juniper.net/v1alpha1
kind: Vrouter
metadata:
  name: contrail-vrouter-nodes
  namespace: contrail
spec:
  agent:
    default:
      xmppAuthEnable: true
      httpServerPort: 18085
    sandesh:
      introspectSslEnable: true
  common:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - ""
            - key: node-role.kubernetes.io/control-plane
              operator: NotIn
              values:
              - ""
            - key: agent-mode
              operator: NotIn
              values:
              - dpdk
    containers:
    - image: enterprise-hub.juniper.net/contrail-container-early/contrail-vrouter-agent:22.4.0.48
      name: contrail-vrouter-agent
    - image: enterprise-hub.juniper.net/contrail-container-early/contrail-init:22.4.0.48
      name: contrail-watcher
    - image: enterprise-hub.juniper.net/contrail-container-early/contrail-telemetry-exporter:22.4.0.48
      name: contrail-vrouter-telemetry-exporter
    initContainers:
    - image: enterprise-hub.juniper.net/contrail-container-early/contrail-init:22.4.0.48
      name: contrail-init
    - image: enterprise-hub.juniper.net/contrail-container-early/contrail-cni-init:22.4.0.48
      name: contrail-cni-init
