apiVersion: contrailstatus.juniper.net/v1alpha1
kind: Contrailstatusmonitor
metadata:
  name: contrail-k8s-contrailstatusmonitor
  namespace: contrail
spec:
  common:
    containers:
    - image: enterprise-hub.juniper.net/contrail-container-early/contrail-k8s-contrailstatusmonitor:22.4.0.48
      name: contrail-k8s-contrailstatusmonitor
    serviceAccountName: contrail-serviceaccount
