apiVersion: configplane.juniper.net/v1alpha1
kind: ApiServer
metadata:
  name: contrail-k8s-apiserver
  namespace: contrail-system
spec:
  common:
    containers:
    - image: hub.juniper.net/cn2/contrail-k8s-apiserver:22.1.0.93
      name: contrail-k8s-apiserver
    nodeSelector:
      node-role.kubernetes.io/master: ""
    serviceAccountName: contrail-system-serviceaccount
