apiVersion: checks.contrail.juniper.net/v1alpha1
kind: ContrailReadiness
metadata:
  name: preflight
spec:
  manifestConfigMapName: deployer-yaml
  tests:
    - name: kernel
      allowFailure: false
      testPodSpec:
        serviceAccountName: contrail-readiness-serviceaccount
        hostNetwork: true
        restartPolicy: Never
        containers:
          - name: kernel-check
            image: hub.juniper.net/cn2/contrail-readiness-checks:22.2.0.1
            imagePullPolicy: Always
            command: ["sh", "-c", "/kernel"]
        tolerations:
          - key: "key"
            operator: "Equal"
            value: "value"
            effect: "NoSchedule"
    - name: ports
      allowFailure: false
      testPodSpec:
        serviceAccountName: contrail-readiness-serviceaccount
        hostNetwork: true
        restartPolicy: Never
        containers:
          - name: ports-check
            image: hub.juniper.net/cn2/contrail-readiness-checks:22.2.0.1
            imagePullPolicy: Always
            command: ["sh", "-c", "/ports"]
        tolerations:
          - key: "key"
            operator: "Equal"
            value: "value"
            effect: "NoSchedule"
    - name: images
      allowFailure: false
      testPodSpec:
        serviceAccountName: contrail-readiness-serviceaccount
        hostNetwork: true
        restartPolicy: Never
        containers:
          - name: images-check
            image: hub.juniper.net/cn2/contrail-readiness-checks:22.2.0.1
            imagePullPolicy: Always
            command: ["sh", "-c", "/images"]
        tolerations:
          - key: "key"
            operator: "Equal"
            value: "value"
            effect: "NoSchedule"
    - name: dns
      allowFailure: false
      testPodSpec:
        serviceAccountName: contrail-readiness-serviceaccount
        hostNetwork: true
        hostPID: true
        hostIPC: true
        restartPolicy: Never
        containers:
          - name: dns-check
            image: hub.juniper.net/cn2/contrail-readiness-checks:22.2.0.1
            imagePullPolicy: Always
            securityContext:
              privileged: true
            command: ["sh", "-c", "/dns"]
            volumeMounts:
            - mountPath: /host
              name: noderoot
        volumes:
        - name: noderoot
          hostPath:
            path: /
        tolerations:
          - key: "key"
            operator: "Equal"
            value: "value"
            effect: "NoSchedule"
    - name: resources
      allowFailure: false
      testPodSpec:
        serviceAccountName: contrail-readiness-serviceaccount
        hostNetwork: true
        restartPolicy: Never
        containers:
          - name: resources-check
            image: hub.juniper.net/cn2/contrail-readiness-checks:22.2.0.1
            imagePullPolicy: Always
            command: ["sh", "-c", "/resources"]
        tolerations:
          - key: "key"
            operator: "Equal"
            value: "value"
            effect: "NoSchedule"
    - name: ntp
      allowFailure: false
      testPodSpec:
        serviceAccountName: contrail-readiness-serviceaccount
        hostNetwork: true
        hostPID: true
        hostIPC: true
        restartPolicy: Never
        containers:
          - name: ntp-check
            image: hub.juniper.net/cn2/contrail-readiness-checks:22.2.0.1
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /host
              name: noderoot
            imagePullPolicy: Always
            command: ["sh", "-c", "/ntp"]
        tolerations:
          - key: "key"
            operator: "Equal"
            value: "value"
            effect: "NoSchedule"
        volumes:
        - name: noderoot
          hostPath:
            path: /
