apiVersion: v1
kind: Namespace
metadata:
  name: contrail-readiness
---
apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
  namespace: contrail-readiness
data:
  .dockerconfigjson: <base64-encoded-credential>
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-readiness-serviceaccount
  namespace: contrail-readiness
imagePullSecrets:
- name: registrypullsecret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contrail-readiness-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contrail-readiness-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-readiness-role
subjects:
  - kind: ServiceAccount
    name: contrail-readiness-serviceaccount
    namespace: contrail-readiness
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contrail-readiness-controller
  namespace: contrail-readiness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contrail-readiness
  template:
    metadata:
      labels:
        app: contrail-readiness
    spec:
      containers:
        - command:
            - sh
            - -c
            - /manager
          image: hub.juniper.net/cn2/contrail-readiness:22.2.0.1
          imagePullPolicy: Always
          name: contrail-readiness
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: contrail-readiness-serviceaccount
      restartPolicy: Always
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
