apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 90-enable-kdump-worker
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            compression: ""
            source: data:,path%20%2Fvar%2Fcrash%0Acore_collector%20makedumpfile%20-l%20--message-level%207%20-d%2031%0A
          mode: 420
          overwrite: true
          path: /etc/kdump.conf
        - contents:
            compression: gzip
            source: data:;base64,H4sIAAAAAAAC/2SPvW4qMRBGe55i5J6rS3oXCFYIkQVElCid5bVnvVbGHuOfTcLTR4lEmlTfqT6dc9g+92e1OfX9+rh93B87den600snxdQcJu2wwC/doFAblMWhObg2jxWInRraqAgjlHfPlQax+Hu6Pp+741YKn6+JiSBmZVIrcgUZC1ZlcfYGCxiXuSVlfdEDoQwYOH9CMCh5HCG2oH+gWZz/mcmTzRiXQX/IB0g6eiNX/yEz15G0KzLyqD2BNsmryCpgmLgmag5q1rEknTFWdc+TEWfMEPlNF/reORjOaC1MWOrdSSwO3Wu3UevL7kmKZbnX7vudFHMgH9tNLL4CAAD//yOBziRXAQAA
          mode: 420
          overwrite: true
          path: /etc/sysconfig/kdump
    systemd:
      units:
        - enabled: true
          name: kdump.service
  kernelArguments:
    - crashkernel=256M
