apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: contrail-deploy
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 29443
  selector:
    app: contrail-k8s-deployer
