apiVersion: apps/v1
kind: Deployment
metadata:
  name: contrail-k8s-deployer
  namespace: contrail-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contrail-k8s-deployer
  template:
    metadata:
      labels:
        app: contrail-k8s-deployer
    spec:
      containers:
      - command:
        - /manager
        - --metrics-addr
        - 127.0.0.1:8081
        - --managed-etcd
        image: hub.juniper.net/cn2/contrail-k8s-deployer:R22.3-9
        name: contrail-k8s-deployer
      initContainers:
      - command:
        - /app/deployer/cert-generator/cert-generator
        env:
        - name: DEFAULT_SECRETS_LIST
          value: |
            [
              {"Namespace":"contrail","Name":"xmpp-tls-vrouter-agent"},
              {"Namespace":"contrail","Name":"xmpp-tls-controller"},
              {"Namespace":"contrail","Name":"sandesh-tls-vrouter-agent"},
              {"Namespace":"contrail","Name":"sandesh-tls-controller"},
              {"Namespace":"contrail","Name":"introspect-tls-client"},
              {"Namespace":"contrail-system","Name":"contrail-api-tls","Dns":"contrail-api.contrail-system.svc"}
            ]
        - name: DISABLE_CERT_MANAGER
          value: "false"
        name: contrail-k8s-cert-generator
        image: hub.juniper.net/cn2/contrail-k8s-cert-generator:R22.3-9
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      serviceAccountName: contrail-deploy-serviceaccount
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
