apiVersion: configplane.juniper.net/v1alpha1
kind: ApiServer
metadata:
  name: contrail-k8s-apiserver
  namespace: contrail-system
spec:
  common:
    containers:
    - image: hub.juniper.net/cn2/contrail-k8s-apiserver:R22.3-9
      name: contrail-k8s-apiserver
    serviceAccountName: contrail-system-serviceaccount