apiVersion: datastore.juniper.net/v1alpha1
kind: Etcd
metadata:
  name: contrail-etcd
  namespace: contrail-system
spec:
  common:
    containers:
    - image: hub.juniper.net/cn2/contrail-etcd:R22.3-9
      name: contrail-etcd
    initContainers:
    - image: hub.juniper.net/cn2/contrail-cert-init:R22.3-9
      name: contrail-cert-init
    - image: hub.juniper.net/cn2/contrail-cert-init:R22.3-9
      name: set-etcd-dir-owner
    serviceAccountName: contrail-system-serviceaccount
  serviceSpec:
    snapshotInterval: 720m
