apiVersion: controlplane.juniper.net/v1alpha1
kind: Control
metadata:
  name: contrail-control
  namespace: contrail
spec:
  xmppAuthEnable: true
  introspectSslEnable: true
  common:
    containers:
    - image: hub.juniper.net/cn2/contrail-control:R22.3-9
      name: contrail-control
    - image: hub.juniper.net/cn2/contrail-telemetry-exporter:R22.3-9
      name: contrail-control-telemetry-exporter
    initContainers:
    - image: hub.juniper.net/cn2/contrail-init:R22.3-9
      name: contrail-init