apiVersion: dataplane.juniper.net/v1alpha1
kind: Vrouter
metadata:
  name: contrail-vrouter-nodes
  namespace: contrail
spec:
  agent:
    default:
      xmppAuthEnable: true
      httpServerPort: 18085
    sandesh:
      introspectSslEnable: true
  common:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - ""
            - key: node-role.kubernetes.io/control-plane
              operator: NotIn
              values:
              - ""
    containers:
    - image: hub.juniper.net/cn2/contrail-vrouter-agent:R22.3-9
      name: contrail-vrouter-agent
    - image: hub.juniper.net/cn2/contrail-init:R22.3-9
      name: contrail-watcher
    - image: hub.juniper.net/cn2/contrail-telemetry-exporter:R22.3-9
      name: contrail-vrouter-telemetry-exporter
    initContainers:
    - image: hub.juniper.net/cn2/contrail-init:R22.3-9
      name: contrail-init
    - image: hub.juniper.net/cn2/contrail-cni-init:R22.3-9
      name: contrail-cni-init
