apiVersion: contrailstatus.juniper.net/v1alpha1
kind: Contrailstatusmonitor
metadata:
  name: contrail-k8s-contrailstatusmonitor
  namespace: contrail
spec:
  common:
    containers:
    - image: enterprise-hub.juniper.net/contrail-container-internal/contrail-k8s-contrailstatusmonitor:23.2.0.156
      name: contrail-k8s-contrailstatusmonitor
    serviceAccountName: contrail-serviceaccount
