apiVersion: dataplane.juniper.net/v1
kind: Vrouter
metadata:
  name: contrail-vrouter-nodes
  namespace: contrail
spec:
  agent:
    default:
      collectors:
      - localhost:6700
      xmppAuthEnable: true
    sandesh:
      introspectSslEnable: true
      sandeshSslEnable: true
  clusterName: multi-cluster
  common:
    containers:
    - image: enterprise-hub.juniper.net/contrail-container-internal/contrail-vrouter-agent:23.3.0.98
      name: contrail-vrouter-agent
    - image: enterprise-hub.juniper.net/contrail-container-internal/contrail-init-coverage:23.3.0.98
      name: contrail-watcher
    - image: enterprise-hub.juniper.net/contrail-container-internal/contrail-telemetry-exporter-coverage:23.3.0.98
      name: contrail-vrouter-telemetry-exporter
    initContainers:
    - image: enterprise-hub.juniper.net/contrail-container-internal/contrail-init-coverage:23.3.0.98
      name: contrail-init
    - image: enterprise-hub.juniper.net/contrail-container-internal/contrail-cni-init:23.3.0.98
      name: contrail-cni-init
  maxUnavailablePercentage: 100%
#
# contrail-network-config configMap is necessary when more than one interface
# is available for control/data traffic. Configure one or more subnets/gateways
# for control/data traffic. In the example below, change the subnet and gateway
# values for your specific topology.
#
# Uncomment below this line to include contrail-network-config configMap
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: contrail-network-config
#   namespace: contrail
# data:
#   networkConfig: |
#     controlDataNetworks:
#     - subnet: 10.16.0.0/24
#       gateway: 10.16.0.254
#     - subnet: 10.10.15.0/24
#       gateway: 10.10.15.254
#     - subnet: 10.10.20.0/24
#       gateway: 10.10.20.254
#     - subnet: 10.10.30.0/24
#       gateway: 10.10.30.254
