apiVersion: v1
kind: Namespace
metadata:
  name: contrail
---
apiVersion: v1
kind: Namespace
metadata:
  name: contrail-deploy
---
apiVersion: v1
kind: Namespace
metadata:
  name: contrail-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: contrail-analytics
---
apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
  namespace: contrail-system
data:
  .dockerconfigjson: <base64-encoded-credential>
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
  namespace: contrail
data:
  .dockerconfigjson: <base64-encoded-credential>
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
  namespace: contrail-deploy
data:
  .dockerconfigjson: <base64-encoded-credential>
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
  namespace: contrail-analytics
data:
  .dockerconfigjson: <base64-encoded-credential>
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-deploy-serviceaccount
  namespace: contrail-deploy
imagePullSecrets:
- name: registrypullsecret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-system-serviceaccount
  namespace: contrail-system
imagePullSecrets:
- name: registrypullsecret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-serviceaccount
  namespace: contrail
imagePullSecrets:
- name: registrypullsecret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-analytics-serviceaccount
  namespace: contrail-analytics
imagePullSecrets:
- name: registrypullsecret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contrail-deploy-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contrail-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contrail-system-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contrail-deploy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-deploy-role
subjects:
- kind: ServiceAccount
  name: contrail-deploy-serviceaccount
  namespace: contrail-deploy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contrail-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-role
subjects:
- kind: ServiceAccount
  name: contrail-serviceaccount
  namespace: contrail
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contrail-system-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-system-role
subjects:
- kind: ServiceAccount
  name: contrail-system-serviceaccount
  namespace: contrail-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contrail-k8s-deployer
  namespace: contrail-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contrail-k8s-deployer
  template:
    metadata:
      labels:
        app: contrail-k8s-deployer
    spec:
      containers:
      - command:
        - sh
        - -c
        - /manager --metrics-addr 127.0.0.1:8081 -central-cluster-config-path /etc/config/central/kubeconfig
        image: enterprise-hub.juniper.net/contrail-container-prod/contrail-k8s-deployer:22.2.0.93
        name: contrail-k8s-deployer
        volumeMounts:
        - mountPath: /etc/config/central
          name: kubeconfig
          readOnly: true
      hostNetwork: true
      initContainers:
      - command:
        - sh
        - -c
        - kustomize build /distributed-crd | kubectl apply -f -
        image: enterprise-hub.juniper.net/contrail-container-prod/contrail-k8s-distributed-crdloader:22.2.0.93
        name: contrail-k8s-distributed-crdloader
      - command:
        - /app/deployer/etcd-cert-discover/etcd-cert-discover
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: enterprise-hub.juniper.net/contrail-container-prod/contrail-k8s-etcd-cert-discover:22.2.0.93
        name: contrail-k8s-etcd-cert-discover
      nodeSelector:
        node-role.kubernetes.io/master: ""
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsUser: 1000
      serviceAccountName: contrail-deploy-serviceaccount
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: kubeconfig
        secret:
          items:
          - key: kubeconfig
            path: kubeconfig
          secretName: central-kubeconfig
  