# Source: cert-manager/templates/webhook-serviceaccount.yaml
apiVersion: v1
imagePullSecrets:
- name: registrypullsecret
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
  labels:
    app: webhook
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: "webhook"
    app.kubernetes.io/version: "v1.13.2"

