apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
  namespace: contrail-system
data:
  .dockerconfigjson: <base64-encoded-credential>
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-system-serviceaccount
  namespace: contrail-system
imagePullSecrets:
- name: registrypullsecret
