#
# contrail-network-config configMap is necessary when using VRRP.
# Configure one or more subnets/gateways for control/data traffic. 
# In the example below, change the subnet and gateway
# values for your specific topology.
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-network-config
  namespace: contrail
data:
  networkConfig: |
    controlDataNetworks:
    - subnet: 10.10.10.0/24
      gateway: 10.10.10.254
    - subnet: 10.10.15.0/24
      gateway: 10.10.15.254
