apiVersion: v1
kind: Namespace
metadata:
  name: contrail
---
apiVersion: v1
kind: Namespace
metadata:
  name: contrail-deploy
---
apiVersion: v1
kind: Namespace
metadata:
  name: contrail-system
---
apiVersion: v1
imagePullSecrets:
- name: registrypullsecret
kind: ServiceAccount
metadata:
  name: contrail-deploy-serviceaccount
  namespace: contrail-deploy
---
apiVersion: v1
imagePullSecrets:
- name: registrypullsecret
kind: ServiceAccount
metadata:
  name: contrail-system-serviceaccount
  namespace: contrail-system
---
apiVersion: v1
imagePullSecrets:
- name: registrypullsecret
kind: ServiceAccount
metadata:
  name: contrail-serviceaccount
  namespace: contrail
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contrail-deploy-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contrail-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contrail-system-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contrail-deploy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-deploy-role
subjects:
- kind: ServiceAccount
  name: contrail-deploy-serviceaccount
  namespace: contrail-deploy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contrail-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-role
subjects:
- kind: ServiceAccount
  name: contrail-serviceaccount
  namespace: contrail
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contrail-system-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-system-role
subjects:
- kind: ServiceAccount
  name: contrail-system-serviceaccount
  namespace: contrail-system
---
apiVersion: v1
data:
  .dockerconfigjson: <base64-encoded-credential>
kind: Secret
metadata:
  name: registrypullsecret
  namespace: contrail-deploy
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: <base64-encoded-credential>
kind: Secret
metadata:
  name: registrypullsecret
  namespace: contrail-system
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: <base64-encoded-credential>
kind: Secret
metadata:
  name: registrypullsecret
  namespace: contrail
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret: ""
  name: contrail-k8s-deployer
  namespace: contrail-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contrail-k8s-deployer
  template:
    metadata:
      labels:
        app: contrail-k8s-deployer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - command:
        - /manager
        - --metrics-addr
        - 127.0.0.1:8081
        - -central-cluster-config-path
        - /etc/config/central/kubeconfig
        image: enterprise-hub.juniper.net/contrail-container-prod/contrail-k8s-deployer:22.4.0.284
        name: contrail-k8s-deployer
        volumeMounts:
        - mountPath: /etc/config/central
          name: kubeconfig
          readOnly: true
      hostNetwork: true
      initContainers:
      - command:
        - kubectl
        - apply
        - -k
        - /distributed-crd
        image: enterprise-hub.juniper.net/contrail-container-prod/contrail-k8s-distributed-crdloader:22.4.0.284
        name: contrail-k8s-distributed-crdloader
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: contrail-deploy-serviceaccount
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: kubeconfig
        secret:
          items:
          - key: kubeconfig
            path: kubeconfig
          secretName: central-kubeconfig
