#
# contrail-network-config configMap is necessary when more than one interface
# is available for control/data traffic. Configure one or more subnets/gateways
# for control/data traffic. In the example below, change the subnet and gateway
# values for your specific topology.
#
# Uncomment below this line to include contrail-network-config configMap
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: contrail-network-config
#   namespace: contrail
# data:
#   networkConfig: |
#     controlDataNetworks:
#     - subnet: 10.16.0.0/24
#       gateway: 10.16.0.254
#     - subnet: 10.16.1.0/24
#       gateway: 10.16.1.254
---
apiVersion: dataplane.juniper.net/v1alpha1
kind: Vrouter
metadata:
  name: contrail-vrouter-masters
  namespace: contrail
spec:
  clusterName: distributed-cluster
  common:
    containers:
    - image: hub.juniper.net/cn2/contrail-vrouter-agent:22.2.0.93
      name: contrail-vrouter-agent
    - image: hub.juniper.net/cn2/contrail-init:22.2.0.93
      name: contrail-watcher
    - image: hub.juniper.net/cn2/contrail-telemetry-exporter:22.2.0.93
      name: contrail-vrouter-telemetry-exporter
    initContainers:
    - image: hub.juniper.net/cn2/contrail-init:22.2.0.93
      name: contrail-init
    - image: hub.juniper.net/cn2/contrail-cni-init:22.2.0.93
      name: contrail-cni-init
    nodeSelector:
      node-role.kubernetes.io/master: ""
---
apiVersion: dataplane.juniper.net/v1alpha1
kind: Vrouter
metadata:
  name: contrail-vrouter-nodes-1
  namespace: contrail
spec:
  clusterName: distributed-cluster
  common:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
# Node selector terms will vary in every deployment
# This is just an example
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - ""
            - key: chassis
              operator: NotIn
              values:
              - "dpdk-worker"
    containers:
    - image: hub.juniper.net/cn2/contrail-vrouter-agent:22.2.0.93
      name: contrail-vrouter-agent
    - image: hub.juniper.net/cn2/contrail-init:22.2.0.93
      name: contrail-watcher
    - image: hub.juniper.net/cn2/contrail-telemetry-exporter:22.2.0.93
      name: contrail-vrouter-telemetry-exporter
    initContainers:
    - image: hub.juniper.net/cn2/contrail-init:22.2.0.93
      name: contrail-init
    - image: hub.juniper.net/cn2/contrail-cni-init:22.2.0.93
      name: contrail-cni-init
  maxUnavailablePercentage: 100%

---
apiVersion: dataplane.juniper.net/v1alpha1
kind: Vrouter
metadata:
  name: contrail-vrouter-nodes-2
  namespace: contrail
spec:
  clusterName: distributed-cluster-1
  agentModeType: dpdk
  common:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
# Node selector terms will vary in every deployment
# This is just an example
          - matchExpressions:
            - key: chassis
              operator: In
              values:
              - "dpdk-worker"
    containers:
    - image: hub.juniper.net/cn2/contrail-vrouter-agent:22.2.0.93
      name: contrail-vrouter-agent
    - image: hub.juniper.net/cn2/contrail-vrouter-dpdk:22.2.0.93
      name: contrail-vrouter-agent-dpdk
      resources:
        limits:
          hugepages-2Mi: 3Gi
        requests:
          memory: 3Gi
    - image: hub.juniper.net/cn2/contrail-init:22.2.0.93
      name: contrail-watcher
    - image: hub.juniper.net/cn2/contrail-telemetry-exporter:22.2.0.93
      name: contrail-vrouter-telemetry-exporter
    initContainers:
    - image: hub.juniper.net/cn2/contrail-init:22.2.0.93
      name: contrail-init
    - image: hub.juniper.net/cn2/contrail-vrouter-kernel-init-dpdk:22.2.0.93
      name: contrail-vrouter-kernel-init-dpdk
    - image: hub.juniper.net/cn2/contrail-cni-init:22.2.0.93
      name: contrail-cni-init
  dpdk:
    cpuCoreMask: 2,3
    dpdkCommandAdditionalArgs: --yield_option 0
    dpdkCtrlThreadMask: 4,5
    dpdkUioDriver: vfio-pci
    hugePages: "8192"
    hugePagesDir: /dev/hugepages
    serviceCoreMask: 4,5
  maxUnavailablePercentage: 100%
