#
# contrail-network-config configMap is necessary when more than one interface
# is available for control/data traffic. Configure one or more subnets/gateways
# for control/data traffic. In the example below, change the subnet and gateway
# values for your specific topology.
#
# Uncomment below this line to include contrail-network-config configMap
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: contrail-network-config
#   namespace: contrail
# data:
#   networkConfig: |
#     controlDataNetworks:
#     - subnet: 10.10.10.0/24
#       gateway: 10.10.10.254
#     - subnet: 10.10.15.0/24
#       gateway: 10.10.15.254
#     - subnet: 10.10.20.0/24
#       gateway: 10.10.20.254
#     - subnet: 10.10.30.0/24
#       gateway: 10.10.30.254
---
apiVersion: dataplane.juniper.net/v1alpha1
kind: Vrouter
metadata:
  name: contrail-vrouter-masters
  namespace: contrail
spec:
  clusterName: distributed-cluster
  common:
    containers:
    - image: hub.juniper.net/cn2/contrail-vrouter-agent:22.2.0.1
      name: contrail-vrouter-agent
    - image: hub.juniper.net/cn2/contrail-init:22.2.0.1
      name: contrail-watcher
    - image: hub.juniper.net/cn2/contrail-telemetry-exporter:22.2.0.1
      name: contrail-vrouter-telemetry-exporter
    initContainers:
    - image: hub.juniper.net/cn2/contrail-init:22.2.0.1
      name: contrail-init
    - image: hub.juniper.net/cn2/contrail-cni-init:22.2.0.1
      name: contrail-cni-init
    nodeSelector:
      node-role.kubernetes.io/master: ""
---
apiVersion: dataplane.juniper.net/v1alpha1
kind: Vrouter
metadata:
  name: contrail-vrouter-nodes-7
  namespace: contrail
spec:
  clusterName: distributed-cluster
  common:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
# Node selector terms will vary in every deployment
# This is just an example
          - matchExpressions:
            - key: chassis
              operator: In
              values:
              - "5d10s3-node3"
    containers:
    - image: hub.juniper.net/cn2/contrail-vrouter-agent:22.2.0.1
      name: contrail-vrouter-agent
    - image: hub.juniper.net/cn2/contrail-init:22.2.0.1
      name: contrail-watcher
    - image: hub.juniper.net/cn2/contrail-telemetry-exporter:22.2.0.1
      name: contrail-vrouter-telemetry-exporter
    initContainers:
    - image: hub.juniper.net/cn2/contrail-init:22.2.0.1
      name: contrail-init
    - image: hub.juniper.net/cn2/contrail-cni-init:22.2.0.1
      name: contrail-cni-init
  maxUnavailablePercentage: 100%

---
apiVersion: dataplane.juniper.net/v1alpha1
kind: Vrouter
metadata:
  name: contrail-vrouter-nodes-8
  namespace: contrail
spec:
  clusterName: distributed-cluster
  common:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
# Node selector terms will vary in every deployment
# This is just an example
          - matchExpressions:
            - key: chassis
              operator: In
              values:
              - "5d10s3-node4"
    containers:
    - image: hub.juniper.net/cn2/contrail-vrouter-agent:22.2.0.1
      name: contrail-vrouter-agent
    - image: hub.juniper.net/cn2/contrail-init:22.2.0.1
      name: contrail-watcher
    - image: hub.juniper.net/cn2/contrail-telemetry-exporter:22.2.0.1
      name: contrail-vrouter-telemetry-exporter
    initContainers:
    - image: hub.juniper.net/cn2/contrail-init:22.2.0.1
      name: contrail-init
    - image: hub.juniper.net/cn2/contrail-cni-init:22.2.0.1
      name: contrail-cni-init
  maxUnavailablePercentage: 100%
---

apiVersion: dataplane.juniper.net/v1alpha1
kind: Vrouter
metadata:
  name: contrail-vrouter-nodes-14
  namespace: contrail
spec:
  clusterName: distributed-cluster
  common:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
# Node selector terms will vary in every deployment
# This is just an example
          - matchExpressions:
            - key: chassis
              operator: In
              values:
              - "5d10s11-node2"
    containers:
    - image: hub.juniper.net/cn2/contrail-vrouter-agent:22.2.0.1
      name: contrail-vrouter-agent
    - image: hub.juniper.net/cn2/contrail-init:22.2.0.1
      name: contrail-watcher
    - image: hub.juniper.net/cn2/contrail-telemetry-exporter:22.2.0.1
      name: contrail-vrouter-telemetry-exporter
    initContainers:
    - image: hub.juniper.net/cn2/contrail-init:22.2.0.1
      name: contrail-init
    - image: hub.juniper.net/cn2/contrail-cni-init:22.2.0.1
      name: contrail-cni-init
  maxUnavailablePercentage: 100%

